name: calcada_da_fama
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: 7.2.0
  scanning_effect: ^1.0.4
  signature: ^5.3.2
  share: any
  path_provider: ^2.0.15
  provider: ^5.0.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: TTTravels
      fonts:
        - asset: assets/fonts/TTTravels-Bold.otf
          weight: 700
        - asset: assets/fonts/TTTravels-Regular.otf
          weight: 400
